# Generated by Django 5.2.8 on 2025-12-14 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('days_above_90f', 'Days Above 90F'), ('days_below_32f', 'Days Below 32F')], max_length=30)),
                ('target_year', models.IntegerField()),
                ('baseline_start_year', models.IntegerField()),
                ('baseline_end_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('baseline_avg_value', models.FloatField(blank=True, null=True)),
                ('delta_value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location')),
            ],
        ),
    ]
