# Generated by Django 5.2.8 on 2025-12-15 19:45

from django.db import migrations
from pathlib import Path
import csv


def seed_demo(apps, schema_editor):
    Location = apps.get_model("weather", "Location")
    WeatherQuery = apps.get_model("weather", "WeatherQuery")

    # Avoid duplicate seeding
    if WeatherQuery.objects.exists():
        return

    
    csv_path = (Path(__file__).resolve().parents[1] / "seed" / "demo_weather_data_v3.csv")

    created_locs = 0
    created_queries = 0

    with csv_path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            loc, loc_created = Location.objects.get_or_create(
                name=row["location_name"],
                defaults={
                    "latitude": float(row["latitude"]),
                    "longitude": float(row["longitude"]),
                },
            )
            if loc_created:
                created_locs += 1

            _, q_created = WeatherQuery.objects.get_or_create(
                location=loc,
                metric=row["metric"],
                target_year=int(row["target_year"]),
                baseline_start_year=int(row["baseline_start_year"]),
                baseline_end_year=int(row["baseline_end_year"]),
                defaults={
                    "target_value": float(row["target_value"]),
                    "baseline_avg_value": float(row["baseline_avg_value"]),
                    "delta_value": float(row["delta_value"]),
                    "status": row["status"],
                },
            )
            if q_created:
                created_queries += 1

    
    print(f"[seed_demo_data_v3] {created_locs} locations created")
    print(f"[seed_demo_data_v3] {created_queries} weather queries created")




class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_demo),
    ]
