# Generated by Django 5.2.8 on 2025-12-14 23:16

from django.db import migrations

def seed_demo_data(apps, schema_editor):
    Location = apps.get_model("weather", "Location")
    WeatherQuery = apps.get_model("weather", "WeatherQuery")

    weather_dir = Path(__file__).resolve().parents[1]
    csv_path = weather_dir / "seed" / "demo_weather_queries.csv"
    if not csv_path.exists():
        raise FileNotFoundError(f"Seed CSV not found: {csv_path}")

    with csv_path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            location_name = (row.get("location_name") or "").strip()
            if not location_name:
                continue

            lat = float(row.get("latitude", ""))
            lon = float(row.get("longitude", ""))

            location_obj, _ = Location.objects.get_or_create(
                name=location_name,
                defaults={"latitude": lat, "longitude": lon},
            )

            metric = (row.get("metric")).strip()
            status = (row.get("status")).strip() or "completed"

            target_year = int(row.get("target_year"))
            baseline_start_year = int(row.get("baseline_start_year"))
            baseline_end_year = int(row.get("baseline_end_year"))

            target_value = float(row.get("target_value"))
            baseline_avg_value = float(row.get("baseline_avg_value"))
            delta_value = float(row.get("delta_value"))
            WeatherQuery.objects.get_or_create(
                location=location_obj,
                metric=metric,
                target_year=target_year,
                baseline_start_year=baseline_start_year,
                baseline_end_year=baseline_end_year,
                defaults={
                    "target_value": target_value,
                    "baseline_avg_value": baseline_avg_value,
                    "delta_value": delta_value,
                    "status": status,
                    "error_message": None,
                },
            )



class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
    ]
