# Generated by Django 5.2.8 on 2025-12-14 23:44

from django.db import migrations
from pathlib import Path
import csv

def seed_demo_data(apps, schema_editor):
    Location = apps.get_model("weather", "Location")
    WeatherQuery = apps.get_model("weather", "WeatherQuery")

    weather_dir = Path(__file__).resolve().parents[1]
    csv_path = weather_dir / "seed" / "demo_weather_data.csv"
    if not csv_path.exists():
        raise FileNotFoundError(f"Seed data CSV not found: {csv_path}")

    with csv_path.open(newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            location_name = (row.get("location_name") or "").strip()
            if not location_name:
                continue

            lat = float(row["latitude"])
            lon = float(row["longitude"])

            location_obj, _ = Location.objects.get_or_create(
                name=location_name,
                defaults={"latitude": lat, "longitude": lon},
            )

            WeatherQuery.objects.get_or_create(
                location=location_obj,
                metric=row["metric"].strip(),
                target_year=int(row["target_year"]),
                baseline_start_year=int(row["baseline_start_year"]),
                baseline_end_year=int(row["baseline_end_year"]),
                defaults={
                    "target_value": float(row["target_value"]),
                    "baseline_avg_value": float(row["baseline_avg_value"]),
                    "delta_value": float(row["delta_value"]),
                    "status": (row.get("status") or "completed").strip(),
                    "error_message": None,
                },
            )

class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_seed_demo_data"),
    ]

    operations = [
        migrations.RunPython(seed_demo_data, reverse_code=migrations.RunPython.noop),
    ]
